### ISSUE TITLE
Creating .wasm file

### ISSUE THREAD

**Issue by Waztom** [eloyfelix/rdkitjs_onnx_multitask#1]
Hi!

Thank you so much for this! Looking at this repo, I was finally able to get RDKit to work in the React app I'm developing. Massive thanks! 

I tried following the original blog post - http://rdkit.blogspot.com/2019/11/introducing-new-rdkit-javascript.html - and just could not get anything to work with often a 'Module.get_mol is not a function' error when calling for example 'Module.get_mol(smiles)'. Noticed this error with some of the other RDKit beta testing pages. 

Was only able to get things working with the .wasm file and using some of your ' onRuntimeInitialized: initRDKitModule().then(function (instance)' to initialise the module. 

For future development - how did you create the .wasm file? Not familiar with generating web assembly files.

**Comment by eloyfelix** [comment]
Hi! Glad you found the demo useful :)

the onRuntimeInitialized thing comes for free when you build the library!

There is a docker image in the RDKit repo that can be used to build the wasm and js files but that it is currently failing to build from master: https://github.com/rdkit/rdkit/issues/4050

To build it you can download the Dockerfile: https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/docker/Dockerfile

change ARG RDKIT_BRANCH=master
to
ARG RDKIT_BRANCH=Release_2021_03

and run the following code:

```#  build the image
docker build -t rdkit/minimallib .

# create a container without running it so we can copy the files
docker create --name dummy rdkit/minimallib
docker cp dummy:/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js .
docker cp dummy:/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.wasm .
docker rm -f dummy
```

**Comment by Waztom** [comment]
OK this is extremely useful and helpful! Thank you so much. I have closed the issue.
